version: '3'

services:
  flask_app:
    container_name: flask_app
    restart: always
    build: ./flask_app
    ports:
      - "8000:8000"
    command: gunicorn -w 1 -b 0.0.0.0:8000 wsgi:server

  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - flask_app
  
  duckdns:
    image: ghcr.io/linuxserver/duckdns
    container_name: duckdns
    environment:
      - TZ=Europe/London
#      - SUBDOMAINS= Subdomains would go here
#      - TOKEN= DuckDNS token would go here
      - LOG_FILE=true
    volumes:
      - /volume1/docker/duckdns:/config
    restart: unless-stopped
